### ISSUE TITLE
JSON.parse invalid json

### ISSUE THREAD

**Issue by chrisjbrown** [markdalgleish/web-app-manifest-loader#3]
In this try

`try {
    var manifest = JSON.parse(source);
  } catch (err) {
    return callback(new Error('Invalid JSON in Web App Manifest'));
  }`

I'm getting the error message Invalid JSON in Web App Manifest

But JSON in my manifest.json is valid

**Comment by chrisjbrown** [comment]
found the issue. Resolved here.

https://github.com/mxstbr/react-boilerplate/issues/580

**Comment by chrisjbrown** [comment]
Nevermind I was using the json-webpack-loader globaly on all json files and that was screwing up the loading of the manifest

**Comment by GabrielGil** [comment]
How did you get to make the json loader to match all the .json files but the manifest? Thank you!

**Comment by YonM** [comment]
@GabrielGil https://github.com/react-boilerplate/react-boilerplate/issues/580
